### ISSUE TITLE
Ошибка автоматического обновления плагина

### ISSUE THREAD

**Issue by azharkov78** [luzmane/emby.kinopoisk.ru#13]
Добрый день
Emby beta 4.9.0.12
Лог ниже:
```
2024-04-17 10:04:03.696 Info TaskManager: Executing Обновить плагин Кинопоиска
2024-04-17 10:04:03.706 Info Server: http/1.1 Response 204 to host1. Time: 23ms. POST http://192.168.7.111:8096/emby/ScheduledTasks/Running/bb74e24cc680f8d1bfbcce5405e1c16a?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=b75e4d12-918a-4209-86e7-9200da79d0b0&X-Emby-Client-Version=4.9.0.12&X-Emby-Token=x_secret6_x&X-Emby-Language=ru
2024-04-17 10:04:03.752 Info HttpClient: GET https://api.github.com/repos/luzmane/emby.kinopoisk.ru/releases/latest
2024-04-17 10:04:04.143 Info HttpClient: Http response 200 from https://api.github.com/repos/luzmane/emby.kinopoisk.ru/releases/latest after 390ms
2024-04-17 10:04:04.193 Info UpdateKinopoiskPluginTask: Converting tag 'v.1.24.1' to '1.24.1'
2024-04-17 10:04:04.198 Info UpdateKinopoiskPluginTask: Update plugin from version 1.23.0 to version 1.24.1
2024-04-17 10:04:04.256 Error InstallationManager: Package installation failed
	*** Error Report ***
	Version: 4.9.0.12
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_armhf.deb
	Operating system: Linux version 6.1.21-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1642 SM
	Framework: .NET 8.0.0
	OS/Process: arm64/arm
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'options.url')
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.ValidateParams(HttpRequestOptions options)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.GetTempFileResponse(HttpRequestOptions options)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.GetTempFile(HttpRequestOptions options)
	   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(IProgress`1 progress, String target, PackageVersionInfo package, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, Boolean isPlugin, IProgress`1 progress, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, Boolean isPlugin, IProgress`1 progress, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void ValidateParams(MediaBrowser.Common.Net.HttpRequestOptions)
	
2024-04-17 10:04:04.274 Error InstallationManager: Error in event handler
	*** Error Report ***
	Version: 4.9.0.12
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_armhf.deb
	Operating system: Linux version 6.1.21-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1642 SM
	Framework: .NET 8.0.0
	OS/Process: arm64/arm
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at Emby.Notifications.NotificationManager._installationManager_PackageInstallationFailed(Object sender, InstallationFailedEventArgs e)
	   at MediaBrowser.Common.Events.EventHelper.TriggerAll[T](EventHandler`1 mainHandler, Object sender, T args, ILogger logger)
	Source: Emby.Notifications
	TargetSite: Void _installationManager_PackageInstallationFailed(System.Object, MediaBrowser.Common.Updates.InstallationFailedEventArgs)
	
2024-04-17 10:04:04.279 Error UpdateKinopoiskPluginTask: Error updating Кинопоиск
	*** Error Report ***
	Version: 4.9.0.12
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_armhf.deb
	Operating system: Linux version 6.1.21-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1642 SM
	Framework: .NET 8.0.0
	OS/Process: arm64/arm
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'options.url')
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.ValidateParams(HttpRequestOptions options)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.GetTempFileResponse(HttpRequestOptions options)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.GetTempFile(HttpRequestOptions options)
	   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(IProgress`1 progress, String target, PackageVersionInfo package, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, Boolean isPlugin, IProgress`1 progress, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, Boolean isPlugin, IProgress`1 progress, CancellationToken cancellationToken)
	   at EmbyKinopoiskRu.ScheduledTasks.UpdateKinopoiskPluginTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
	Source: Emby.Server.Implementations
	TargetSite: Void ValidateParams(MediaBrowser.Common.Net.HttpRequestOptions)
	
2024-04-17 10:04:04.279 Info TaskManager: Обновить плагин Кинопоиска Completed after 0 minute(s) and 0 seconds
```

**Comment by azharkov78** [comment]
Увидел что новая версия вышла.
