### ISSUE TITLE
Вопрос: может ли плагин сканировать медиатеки на предмет новых медиа?

### ISSUE THREAD

**Issue by reyist** [luzmane/emby.kinopoisk.ru#17]
Приветствую!

Немного вводной простыни, чтобы пояснить, что я имею ввиду:

Я пытаюсь перенести Эмби с Synology NAS на LXC контейнер, соответственно все медиа файлы хранятся на насе. Вроде логично, чтобы все файлы там и остались, а к LXC просто примонтировать по CIFS/SMB каталоги с фильмами/сериалами/фото. Я все это сделал, но встала большая проблема со сканированием новых медиа-файлов. 

CIFS/SMB и даже NFS не поддерживает **_inotify_**, поэтому каждый раз приходится или вручную запускать сканирование медиатеки или через планировщик. Планировщик неудобен тем, что ты, к примеру, каждые  30м запускаешь скан всех медиатек, что прилично так грузит сервер, в том числе из-за количества медиа (а их уже накопилось прилично). Если при просмотре с одновременным транскодированием наложить еще и задачу скана медиатеки, то случаются подлагивания, а при активном использовании этой частый сценарий.

Нашел скрипт, который через утилиту _**inotifywait**_ периодически запускает проверку папок с фильмами/сериалами/фото на изменения и через Emby API инициирует скан медиатек:

```
 \opt\bin\inotifywait -m -r -e create,modify --format '%w%f' /volume1/movies  /volume1/tv  /volume1/photo | while read NEWFILE; do
    curl -X 'POST' \
	  "http://server:serverport/emby/Library/Refresh?api_key=myapikey" \
      -H 'accept: */*' \
      -d ''
    sleep 10m
done
```
Но тут снова проблемы... Доступ по CIFS/SMB теперь уже прилично грузит NAS (из-за количества медиа), что в свою очередь каждый раз инициирует кучу запросов к API TMDB, IMDB, Кинопоиска (исходя из логов). В общем очень нерационально, что по запросам, что по лишней нагрузке на NAS (на котором и так много всего крутится).

А теперь к самому вопросу :)
До всего этого я заметил, что новое медиа все же через некоторое время появляется, примерно на следующий день - точно не замерял. Когда полез в логи, увидел, что загрузку метаданных и картинок начинает плагин Кинопоиска. Т.е. он видимо как-то просматривает медиатеку и начинает их скачку  - поправьте, если не прав.

Так вот, можно ли  как-то сделать, чтобы плагин опознавал новое медиа по какому-то настраиваемому рассписанию? Ну или может есть какое-то другое решение?

**Comment by luzmane** [comment]
Здравствуйте!
Скорее всего плагин Кинопоиска стоит первый в библиотеке на получение метаданных, поэтому он и "начинает" поход за метой.
Может быть эта задача запускает скан библиотек:
![image](https://github.com/luzmane/emby.kinopoisk.ru/assets/11422326/aa9043d5-8268-44a6-8666-86e48f14ea83)

Плагин не запускает разпознавание - он им (обновлением данных) используется для получения информации с API.

LXC контейнер - это обязательно или докер тоже подойдёт? У меня Emby бегает на docker'e через обратный прокси. Сами файлы на так называемом NAS'e - сервер с debian'ом, на котором и бежит этот самый докер. Никаких проблем с задержками не имею, видео появляется как только оказывается в папке на debian. Могу скинуть docker-compose прокси и Emby.

**Comment by reyist** [comment]
Да я думаю дело больше в том, что если в целом в Emby сервер (неважно, докер или deb пакет) для хранения медиа на другой машине использовать удаленную файловую систему, на типа smb или nfs, то галка в настройках медиатеки "Включить отслеживание в реальном времени" просто перестает работать, как раз из-за отсутствия поддержки inotify у этих FS. 

В этой ветке, вроде, как раз об этом и говорят: https://emby.media/community/index.php?/topic/125797-changes-to-library-directories-not-causing-a-library-scan/

А костыль со скриптом в целом работает, но, кмк, излишне грузит обе системы - как сервер, так и удаленную шару с файлами. Плюс генерится просто куча мусорных логов на NAS'е и Emby сервере на постоянной основе. Очень накладно, грубо говоря, раз в 20-30 мин, сканировать объемную удаленную шару и потом заново все медиатеки.

Вот поэтому пытаюсь как-то решить эту проблему, думал, что плагин как-то это делает) Но скорее всего да, просто запускался скан медиа библиотеки.

**Comment by luzmane** [comment]
а что за задача в логах бежит? как она в логах называется. ведь она не обновляет метаданные для всех, а только для тех видео, что отсутствуют. может можно как-то запускать именно её, а не глобальное обновление библиотек?

**Comment by reyist** [comment]
```
2024-05-22 10:31:15.662 Info Server: http/1.1 POST http://192.168.1.89:8096/emby/Library/Refresh?api_key=x_secret2_x. UserAgent: curl/7.86.0
2024-05-22 10:31:15.673 Info Server: http/1.1 Response 204 to host4. Time: 10ms. POST http://192.168.1.89:8096/emby/Library/Refresh?api_key=x_secret2_x
2024-05-22 10:31:15.673 Info TaskManager: Queueing task RefreshMediaLibraryTask
2024-05-22 10:31:15.673 Info TaskManager: Executing Scan media library
2024-05-22 10:31:15.939 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /opt/emby-server/bin/ffprobe -i file:"/mnt/movies/The Ministry of Ungentlemanly Warfare (2024) [imdbid-tt5177120]/The Ministry of Ungentlemanly Warfare (2024) {imdb-tt5177120} [WEBDL-1080p][EAC3 5.1][x264]-EniaHD.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-05-22 10:31:15.958 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-05-22 10:31:15.960 Info KpMovieLocalMetadata: GetMetadata by ItemInfo: '/mnt/movies/The Ministry of Ungentlemanly Warfare (2024) [imdbid-tt5177120]/The Ministry of Ungentlemanly Warfare (2024) {imdb-tt5177120} [WEBDL-1080p][EAC3 5.1][x264]-EniaHD.mkv'
2024-05-22 10:31:15.964 Info KpMovieProvider: GetMetadata by MovieInfo:'Министерство неджентльменских дел', '2024'
2024-05-22 10:31:15.964 Info KinopoiskRu: Fetching kinopoiskapiunofficial.tech service
2024-05-22 10:31:15.964 Info KinopoiskUnofficialService: Searching movie by movie id '4414587'
2024-05-22 10:31:15.964 Info KinopoiskUnofficialApi: Sending request to https://kinopoiskapiunofficial.tech/api/v2.2/films/4414587
2024-05-22 10:31:15.964 Info KinopoiskUnofficialApi: Received response: '{"kinopoiskId":4414587,"kinopoiskHDId":"4a0e81d5d0584c52b61baaa6e1d1ff71","imdbId":"tt5177120","nameRu":"Министерство неджентльменских дел","nameEn":null,"nameOriginal":"The Ministry of Ungentlemanly Warfare","posterUrl":"https://kinopoiskapiunofficial.tech/images/posters/kp/4414587.jpg","posterUrlPreview":"https://kinopoiskapiunofficial.tech/images/posters/kp_small/4414587.jpg","coverUrl":"https://avatars.mds.yandex.net/get-ott/224348/2a0000018f3e89a200cf1fd5a46d92eb7fc5/orig","logoUrl":null,"reviewsCount":6,"ratingGoodReview":17.0,"ratingGoodReviewVoteCount":1,"ratingKinopoisk":7.1,"ratingKinopoiskVoteCount":6099,"ratingImdb":7.3,"ratingImdbVoteCount":8721,"ratingFilmCritics":6.6,"ratingFilmCriticsVoteCount":31,"ratingAwait":99.0,"ratingAwaitCount":19970,"ratingRfCritics":null,"ratingRfCriticsVoteCount":0,"webUrl":"https://www.kinopoisk.ru/film/4414587/","year":2024,"filmLength":120,"slogan":null,"description":"1942 год, Великобритания. Они — лучшие из лучших. Отпетые авантюристы и первоклассные спецы, привыкшие действовать в одиночку. Но когда на кону стоит судьба всего мира, им приходится объединиться в сверхсекретное боевое подразделение и отправиться на выполнение дерзкой миссии против нацистов. Теперь их дело — война, и вести они её будут совершенно не по-джентльменски.","shortDescription":"Отряду авантюристов поручают невыполнимую миссию. Новый фильм Гая Ричи и продюсера «Пиратов Карибского моря»","editorAnnotation":"В мае на Кинопоиске","isTicketsAvailable":false,"productionStatus":null,"type":"FILM","ratingMpaa":"r","ratingAgeLimits":"age18","countries":[{"country":"США"},{"country":"Великобритания"},{"country":"Турция"}],"genres":[{"genre":"драма"},{"genre":"боевик"},{"genre":"военный"},{"genre":"история"}],"startYear":null,"endYear":null,"serial":false,"shortFilm":false,"completed":false,"hasImax":false,"has3D":false,"lastSync":"2024-05-06T18:07:16.522463"}'
2024-05-22 10:31:15.964 Info KinopoiskUnofficialService: Movie found by provider ID, Kinopoisk ID: '4414587'
2024-05-22 10:31:15.964 Info KinopoiskUnofficialService: Movie 'Министерство неджентльменских дел' with Кинопоиск id '4414587' found
2024-05-22 10:31:15.964 Info KinopoiskUnofficialApi: Sending request to https://kinopoiskapiunofficial.tech/api/v1/staff?filmId=4414587
```
Вроде просто POST запрос на API emby/Library/Refresh. А потом плагин Кинопоиска находит по очереди метаданные по содержимому библиотек. 

Дальше запросы к api.themoviedb.org:
```
2024-05-22 10:31:16.266 Info HttpClient: GET https://api.themoviedb.org/3/configuration/primary_translations?api_key=x_secret3_x
2024-05-22 10:31:16.273 Error HttpClient: Error getting response from https://api.themoviedb.org/3/configuration/primary_translations?api_key=x_secret3_x
	*** Error Report ***
	Version: 4.8.7.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Linux version 6.5.11-8-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-8
	Framework: .NET 6.0.25
	OS/Process: x64/x64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 2
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: Connection refused (api.themoviedb.org:443)
	 ---> System.Net.Sockets.SocketException (111): Connection refused
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
	   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
	   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.Net.Sockets.SocketException: Connection refused
	Source: System.Net.Sockets
	TargetSite: Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
	   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```
И так проходит по всем фильмам и сериалам.

Вот обращения на удаленную шару:
![2024-05-22_11-17-24](https://github.com/luzmane/emby.kinopoisk.ru/assets/129279441/6207e62e-3ef2-4909-8afd-58419ab3b9c9)

Т.е. он все равно проходит по всем медиатекам, а не только, где данные сменились.

**Comment by luzmane** [comment]
можно поэкспериментировать. например, создать запрос, который бы по переданному пути файла запускал бы его добавление и распознавание..
чуть освобожусь на работе, покопаю в этом направлении.
тикет пока не закрываю

**Comment by reyist** [comment]
Долго помучив  chatgpt родили вот такое:

```
#!/bin/bash

EMBY_SERVER="http://192.168.1.3:8096"
API_KEY="1234567890"
MOVIES_LIBRARY_ID="6153"
TV_LIBRARY_ID="7245"
LAST_UPDATE_FILE="/tmp/emby_last_update"

# Функция для отправки запроса на обновление
update_library() {
    local ITEM_ID=$1
    local LIBRARY_PATH=$2
    local CURRENT_TIME=$(date +%s)
    local LAST_UPDATE=0

    # Проверяем время последнего обновления
    if [ -f "$LAST_UPDATE_FILE" ]; then
        LAST_UPDATE=$(cat "$LAST_UPDATE_FILE")
    fi

    # Если с момента последнего обновления прошло достаточно времени, обновляем библиотеку
    if [ $((CURRENT_TIME - LAST_UPDATE)) -gt 300 ]; then # 300 секунд (5 минут) задержки
        echo $CURRENT_TIME > "$LAST_UPDATE_FILE"
        curl -X 'POST' \
        "$EMBY_SERVER/emby/Items/$ITEM_ID/Refresh?Recursive=true&ImageRefreshMode=Default&MetadataRefreshMode=Default&ReplaceAllImages=false&ReplaceAllMetadata=false&api_key=$API_KEY" \
        -H 'accept: */*' \
        -d ''
    else
        echo "Последнее обновление было слишком недавно. Пропускаем обновление."
    fi
}

# Основной цикл мониторинга
/opt/bin/inotifywait -m -r -e create,modify,delete --format '%w%f' /volume1/data/media/movies /volume1/data/media/tv | while read NEWFILE; do
    if [[ "$NEWFILE" == /volume1/data/media/movies/* ]]; then
        update_library "$MOVIES_LIBRARY_ID" "/volume1/data/media/movies"
    elif [[ "$NEWFILE" == /volume1/data/media/tv/* ]]; then
        update_library "$TV_LIBRARY_ID" "/volume1/data/media/tv"
    fi
done
```
Он смотрит типа так - если были ли изменения в библиотеках за последние 5 минут, то тогда посылает запрос на обновление конкретной медиатеки (фильмы или сериалы). Минус в том, что если файлы менялись раньше установленного времени (5 минут) то обновление не произойдет, т.к. запрос не отправит.

Это лучшее, что я пока смог вымучить у gpt, все остальные варианты инициировали  зацикленное обновление библиотек, пока не перезапустишь сервер или по PID не убьешь процесс скрипта.

**Comment by luzmane** [comment]
не знал, что в API Emby есть возможность обновлять конкретную библиотеку. 
по мне так решение отличное - окно в 5 минут не критично (это всё таки не аппликация реального времени, а домашний кинотеатр). 
спасибо за инфу!
