### ISSUE TITLE
Ошибка при обновлении плагина 1.18.1

### ISSUE THREAD

**Issue by reyist** [luzmane/emby.kinopoisk.ru#8]
Приветствую, использую Emby 4.7.14.0 на Synology NAS ( DSM 7.2-64570 Update 3 ).
Со вчерашнего дня перестала работать задача в шедулере по обновлению плагина.
Текст ошибки:
 Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at EmbyKinopoiskRu.ScheduledTasks.UpdateKinopoiskPluginTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

**Comment by luzmane** [comment]
доброе время суток!
проверил у себя - тоже самое. скоро выпущу обновление

**Comment by luzmane** [comment]
К сожалению, проблема в старом коде. Для обновления придётся удалить старую версию плагина и поставить новую вручную
